version: '3'
services:
    web:
        environment:
            - CHOKIDAR_USEPOLLING=true
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            #do not to map a folder against app/node_modules inside the container
            - /app/node_modules
            #map . outside of the container(current container) to the app folder inside the container
            - .:/app

    tests:
        environment:
            - CHOKIDAR_USEPOLLING=true
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            #do not to map a folder against app/node_modules inside the container
            - /app/node_modules
            #map . outside of the container(current container) to the app folder inside the container
            - .:/app
        command: ["npm", "run", "test"]
